### ISSUE TITLE
Imprint/Privacy/License routes aren’t working. 

### ISSUE THREAD

**Issue by liam-k** [ISH-Gruppe/screenario#102]
### Which component(s) are the source of the bug?

Don't known / other

### A summary of the issue. 
https://screenar.io/impressum, https://screenar.io/datenschutz & https://screenar.io/lizenzen return a 404. I can’t reproduce this locally, it’s likely a server-side issue, related to our recent move to render.com. 

### Please describe the steps to reproduce this bug

Visit the links via the official domain, not locally. 

### Is this a regression?

Yes though not code-related

**Comment by s-gbz** [comment]
This bug was caused by a React issue on render's site.
Fixed.
